### ISSUE TITLE
How it works 

### ISSUE THREAD

**Issue by Doutianbao** [jwickfil7/wrtn.ai#2]
Please tell us how it works:)

**Comment by h053698** [comment]
This project use api from the wrtn.ai website, which provides conversational AI service such as gpt3.5. gpt4, etc.
You can sign up at https://wrtn.ai and use this library to use gpt3.5, gpt4, PaLM2 models in python without paying. but its slow :)

**Comment by Doutianbao** [comment]
> This project use api from the wrtn.ai website, which provides conversational AI service such as gpt3.5. gpt4, etc.
> You can sign up at https://wrtn.ai and use this library to use gpt3.5, gpt4, PaLM2 models in python without paying. but its slow :)
> 

Thank you so much.
Is it possible that a detailed readme or use description would be made someday?

**Comment by h053698** [comment]
This project has no plans for updates (readme). Thank you for your interest in this project.

**Comment by Doutianbao** [comment]
> This project has no plans for updates (readme). Thank you for your interest in this project.

Get it.
Thank you
